// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm0U-WwrCq7gikLM4JcvoScTi0QJiLx-g',
    appId: '1:725138577826:web:906382f087285520843afb',
    messagingSenderId: '725138577826',
    projectId: 'stack-84ff9',
    authDomain: 'stack-84ff9.firebaseapp.com',
    storageBucket: 'stack-84ff9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFUoxtPzXR-qOeTja92DNE1fSr9JDnW9c',
    appId: '1:725138577826:android:b59dfe41371f615d843afb',
    messagingSenderId: '725138577826',
    projectId: 'stack-84ff9',
    storageBucket: 'stack-84ff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDA8Ouydnw9pNhkug7Onbm0ut1h893ffc',
    appId: '1:725138577826:ios:8973e73830d087bd843afb',
    messagingSenderId: '725138577826',
    projectId: 'stack-84ff9',
    storageBucket: 'stack-84ff9.appspot.com',
    iosBundleId: 'com.example.stack',
  );
}
